version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: satyacheck-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=satyacheck
    volumes:
      - mongodb_data:/data/db
    networks:
      - satyacheck-network

  springboot-api:
    image: adoptopenjdk/openjdk11:alpine-jre
    container_name: satyacheck-springboot-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/satyacheck
    networks:
      - satyacheck-network
    volumes:
      - ./test-api.sh:/test-api.sh
    command: sh /test-api.sh

networks:
  satyacheck-network:
    driver: bridge

volumes:
  mongodb_data: